// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/skip-the-line/internal/notification"
	"sync"
)

// Ensure, that GitHubTeamResolverMock does implement notification.GitHubTeamResolver.
// If this is not the case, regenerate this file with moq.
var _ notification.GitHubTeamResolver = &GitHubTeamResolverMock{}

// GitHubTeamResolverMock is a mock implementation of notification.GitHubTeamResolver.
//
//	func TestSomethingThatUsesGitHubTeamResolver(t *testing.T) {
//
//		// make and configure a mocked notification.GitHubTeamResolver
//		mockedGitHubTeamResolver := &GitHubTeamResolverMock{
//			GetTeamMembersFunc: func(ctx context.Context, org string, team string) ([]string, error) {
//				panic("mock out the GetTeamMembers method")
//			},
//		}
//
//		// use mockedGitHubTeamResolver in code that requires notification.GitHubTeamResolver
//		// and then make assertions.
//
//	}
type GitHubTeamResolverMock struct {
	// GetTeamMembersFunc mocks the GetTeamMembers method.
	GetTeamMembersFunc func(ctx context.Context, org string, team string) ([]string, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetTeamMembers holds details about calls to the GetTeamMembers method.
		GetTeamMembers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Org is the org argument value.
			Org string
			// Team is the team argument value.
			Team string
		}
	}
	lockGetTeamMembers sync.RWMutex
}

// GetTeamMembers calls GetTeamMembersFunc.
func (mock *GitHubTeamResolverMock) GetTeamMembers(ctx context.Context, org string, team string) ([]string, error) {
	if mock.GetTeamMembersFunc == nil {
		panic("GitHubTeamResolverMock.GetTeamMembersFunc: method is nil but GitHubTeamResolver.GetTeamMembers was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Org  string
		Team string
	}{
		Ctx:  ctx,
		Org:  org,
		Team: team,
	}
	mock.lockGetTeamMembers.Lock()
	mock.calls.GetTeamMembers = append(mock.calls.GetTeamMembers, callInfo)
	mock.lockGetTeamMembers.Unlock()
	return mock.GetTeamMembersFunc(ctx, org, team)
}

// GetTeamMembersCalls gets all the calls that were made to GetTeamMembers.
// Check the length with:
//
//	len(mockedGitHubTeamResolver.GetTeamMembersCalls())
func (mock *GitHubTeamResolverMock) GetTeamMembersCalls() []struct {
	Ctx  context.Context
	Org  string
	Team string
} {
	var calls []struct {
		Ctx  context.Context
		Org  string
		Team string
	}
	mock.lockGetTeamMembers.RLock()
	calls = mock.calls.GetTeamMembers
	mock.lockGetTeamMembers.RUnlock()
	return calls
}
