// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/skip-the-line/internal/notification"
	"github.com/skip-the-line/internal/notifier"
	"sync"
)

// Ensure, that NotifierMock does implement notification.Notifier.
// If this is not the case, regenerate this file with moq.
var _ notification.Notifier = &NotifierMock{}

// NotifierMock is a mock implementation of notification.Notifier.
//
//	func TestSomethingThatUsesNotifier(t *testing.T) {
//
//		// make and configure a mocked notification.Notifier
//		mockedNotifier := &NotifierMock{
//			LookupUserByEmailFunc: func(ctx context.Context, email string) (string, error) {
//				panic("mock out the LookupUserByEmail method")
//			},
//			SendNotificationFunc: func(ctx context.Context, recipientID string, msg notifier.Message) error {
//				panic("mock out the SendNotification method")
//			},
//		}
//
//		// use mockedNotifier in code that requires notification.Notifier
//		// and then make assertions.
//
//	}
type NotifierMock struct {
	// LookupUserByEmailFunc mocks the LookupUserByEmail method.
	LookupUserByEmailFunc func(ctx context.Context, email string) (string, error)

	// SendNotificationFunc mocks the SendNotification method.
	SendNotificationFunc func(ctx context.Context, recipientID string, msg notifier.Message) error

	// calls tracks calls to the methods.
	calls struct {
		// LookupUserByEmail holds details about calls to the LookupUserByEmail method.
		LookupUserByEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
		// SendNotification holds details about calls to the SendNotification method.
		SendNotification []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RecipientID is the recipientID argument value.
			RecipientID string
			// Msg is the msg argument value.
			Msg notifier.Message
		}
	}
	lockLookupUserByEmail sync.RWMutex
	lockSendNotification  sync.RWMutex
}

// LookupUserByEmail calls LookupUserByEmailFunc.
func (mock *NotifierMock) LookupUserByEmail(ctx context.Context, email string) (string, error) {
	if mock.LookupUserByEmailFunc == nil {
		panic("NotifierMock.LookupUserByEmailFunc: method is nil but Notifier.LookupUserByEmail was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockLookupUserByEmail.Lock()
	mock.calls.LookupUserByEmail = append(mock.calls.LookupUserByEmail, callInfo)
	mock.lockLookupUserByEmail.Unlock()
	return mock.LookupUserByEmailFunc(ctx, email)
}

// LookupUserByEmailCalls gets all the calls that were made to LookupUserByEmail.
// Check the length with:
//
//	len(mockedNotifier.LookupUserByEmailCalls())
func (mock *NotifierMock) LookupUserByEmailCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockLookupUserByEmail.RLock()
	calls = mock.calls.LookupUserByEmail
	mock.lockLookupUserByEmail.RUnlock()
	return calls
}

// SendNotification calls SendNotificationFunc.
func (mock *NotifierMock) SendNotification(ctx context.Context, recipientID string, msg notifier.Message) error {
	if mock.SendNotificationFunc == nil {
		panic("NotifierMock.SendNotificationFunc: method is nil but Notifier.SendNotification was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		RecipientID string
		Msg         notifier.Message
	}{
		Ctx:         ctx,
		RecipientID: recipientID,
		Msg:         msg,
	}
	mock.lockSendNotification.Lock()
	mock.calls.SendNotification = append(mock.calls.SendNotification, callInfo)
	mock.lockSendNotification.Unlock()
	return mock.SendNotificationFunc(ctx, recipientID, msg)
}

// SendNotificationCalls gets all the calls that were made to SendNotification.
// Check the length with:
//
//	len(mockedNotifier.SendNotificationCalls())
func (mock *NotifierMock) SendNotificationCalls() []struct {
	Ctx         context.Context
	RecipientID string
	Msg         notifier.Message
} {
	var calls []struct {
		Ctx         context.Context
		RecipientID string
		Msg         notifier.Message
	}
	mock.lockSendNotification.RLock()
	calls = mock.calls.SendNotification
	mock.lockSendNotification.RUnlock()
	return calls
}
