// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/skip-the-line/internal/notification"
	"sync"
)

// Ensure, that NotificationServicerMock does implement notification.NotificationServicer.
// If this is not the case, regenerate this file with moq.
var _ notification.NotificationServicer = &NotificationServicerMock{}

// NotificationServicerMock is a mock implementation of notification.NotificationServicer.
//
//	func TestSomethingThatUsesNotificationServicer(t *testing.T) {
//
//		// make and configure a mocked notification.NotificationServicer
//		mockedNotificationServicer := &NotificationServicerMock{
//			NotifyFunc: func(ctx context.Context, eventType string, event any) error {
//				panic("mock out the Notify method")
//			},
//		}
//
//		// use mockedNotificationServicer in code that requires notification.NotificationServicer
//		// and then make assertions.
//
//	}
type NotificationServicerMock struct {
	// NotifyFunc mocks the Notify method.
	NotifyFunc func(ctx context.Context, eventType string, event any) error

	// calls tracks calls to the methods.
	calls struct {
		// Notify holds details about calls to the Notify method.
		Notify []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// EventType is the eventType argument value.
			EventType string
			// Event is the event argument value.
			Event any
		}
	}
	lockNotify sync.RWMutex
}

// Notify calls NotifyFunc.
func (mock *NotificationServicerMock) Notify(ctx context.Context, eventType string, event any) error {
	if mock.NotifyFunc == nil {
		panic("NotificationServicerMock.NotifyFunc: method is nil but NotificationServicer.Notify was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		EventType string
		Event     any
	}{
		Ctx:       ctx,
		EventType: eventType,
		Event:     event,
	}
	mock.lockNotify.Lock()
	mock.calls.Notify = append(mock.calls.Notify, callInfo)
	mock.lockNotify.Unlock()
	return mock.NotifyFunc(ctx, eventType, event)
}

// NotifyCalls gets all the calls that were made to Notify.
// Check the length with:
//
//	len(mockedNotificationServicer.NotifyCalls())
func (mock *NotificationServicerMock) NotifyCalls() []struct {
	Ctx       context.Context
	EventType string
	Event     any
} {
	var calls []struct {
		Ctx       context.Context
		EventType string
		Event     any
	}
	mock.lockNotify.RLock()
	calls = mock.calls.Notify
	mock.lockNotify.RUnlock()
	return calls
}
