// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/skip-the-line/internal/notification"
	"sync"
)

// Ensure, that SlackNotifierMock does implement notification.SlackNotifier.
// If this is not the case, regenerate this file with moq.
var _ notification.SlackNotifier = &SlackNotifierMock{}

// SlackNotifierMock is a mock implementation of notification.SlackNotifier.
//
//	func TestSomethingThatUsesSlackNotifier(t *testing.T) {
//
//		// make and configure a mocked notification.SlackNotifier
//		mockedSlackNotifier := &SlackNotifierMock{
//			LookupUserByEmailFunc: func(ctx context.Context, email string) (string, error) {
//				panic("mock out the LookupUserByEmail method")
//			},
//			SendDMFunc: func(ctx context.Context, email string, message string) error {
//				panic("mock out the SendDM method")
//			},
//		}
//
//		// use mockedSlackNotifier in code that requires notification.SlackNotifier
//		// and then make assertions.
//
//	}
type SlackNotifierMock struct {
	// LookupUserByEmailFunc mocks the LookupUserByEmail method.
	LookupUserByEmailFunc func(ctx context.Context, email string) (string, error)

	// SendDMFunc mocks the SendDM method.
	SendDMFunc func(ctx context.Context, slackUserID string, message string) error

	// calls tracks calls to the methods.
	calls struct {
		// LookupUserByEmail holds details about calls to the LookupUserByEmail method.
		LookupUserByEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
		// SendDM holds details about calls to the SendDM method.
		SendDM []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SlackUserID is the slackUserID argument value.
			SlackUserID string
			// Message is the message argument value.
			Message string
		}
	}
	lockLookupUserByEmail sync.RWMutex
	lockSendDM            sync.RWMutex
}

// LookupUserByEmail calls LookupUserByEmailFunc.
func (mock *SlackNotifierMock) LookupUserByEmail(ctx context.Context, email string) (string, error) {
	if mock.LookupUserByEmailFunc == nil {
		panic("SlackNotifierMock.LookupUserByEmailFunc: method is nil but SlackNotifier.LookupUserByEmail was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockLookupUserByEmail.Lock()
	mock.calls.LookupUserByEmail = append(mock.calls.LookupUserByEmail, callInfo)
	mock.lockLookupUserByEmail.Unlock()
	return mock.LookupUserByEmailFunc(ctx, email)
}

// LookupUserByEmailCalls gets all the calls that were made to LookupUserByEmail.
// Check the length with:
//
//	len(mockedSlackNotifier.LookupUserByEmailCalls())
func (mock *SlackNotifierMock) LookupUserByEmailCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockLookupUserByEmail.RLock()
	calls = mock.calls.LookupUserByEmail
	mock.lockLookupUserByEmail.RUnlock()
	return calls
}

// SendDM calls SendDMFunc.
func (mock *SlackNotifierMock) SendDM(ctx context.Context, slackUserID string, message string) error {
	if mock.SendDMFunc == nil {
		panic("SlackNotifierMock.SendDMFunc: method is nil but SlackNotifier.SendDM was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		SlackUserID string
		Message     string
	}{
		Ctx:         ctx,
		SlackUserID: slackUserID,
		Message:     message,
	}
	mock.lockSendDM.Lock()
	mock.calls.SendDM = append(mock.calls.SendDM, callInfo)
	mock.lockSendDM.Unlock()
	return mock.SendDMFunc(ctx, slackUserID, message)
}

// SendDMCalls gets all the calls that were made to SendDM.
// Check the length with:
//
//	len(mockedSlackNotifier.SendDMCalls())
func (mock *SlackNotifierMock) SendDMCalls() []struct {
	Ctx         context.Context
	SlackUserID string
	Message     string
} {
	var calls []struct {
		Ctx         context.Context
		SlackUserID string
		Message     string
	}
	mock.lockSendDM.RLock()
	calls = mock.calls.SendDM
	mock.lockSendDM.RUnlock()
	return calls
}
